FROM python:slim-stretch

RUN apt update && apt install -y git && rm -rf /var/lib/apt/lists/* \
  && pip install --no-cache-dir pygments==2.8.1 pymdown-extensions==8.1.1 mkdocs==1.1.2 mkdocs-material==7.0.6 mkdocs-minify-plugin==0.4.0 mkdocs-redirects==1.0.3 mkdocs-with-pdf==0.8.3 \
  && pip install git+https://github.com/linkchecker/linkchecker.git

COPY ./dev/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /site
COPY . .
VOLUME ["/site"]

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]
