# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

namespaceToDeploy: "multiarch-demo-test"

replicaCount: 1
logLevel: "debug"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 8080
  productcatalogservice:
    svcName: "productcatalogservice"
    port: 3550
  currencyservice:
    svcName: "currencyservice"
    port: 7000
  cartservice:
    svcName: "cartservice"
    port: 7070
  recommendationservice:
    svcName: "recommendationservice"
    port: 8080
  shippingservice:
    svcName: "shippingservice"
    port: 50051
  checkoutservice:
    svcName: "checkoutservice"
    port: 5050
  adservice:
    svcName: "adservice"
    port: 9555

nameOverride: ""
fullnameOverride: ""

service:
  enabled: true
  type: ClusterIP
  port: 8080

submariner:
  enabled: false

route:
  enabled: false

ingress:
  enabled: true
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

  #  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

jaegerConfigName: jaeger-config
jaegerSecretName: jaeger-access

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: multicloud-demo

runtime: golang

serviceMesh:
  sidecar: true
